#!/usr/bin/env python3
"""Hermiticity check and repair of the tight-binding blocks in the _tb.dat reader.

A physical model has H_ij(R) = conj(H_ji(-R)), S likewise, and r_ij(R) = conj(r_ji(-R)) + R S_ij(R) (the R S term is
zero for orthonormal Wannier functions). opticx's k-space kernels read only the LOWER triangle, so the reader must
(a) complete a block stored as its lower triangle only (SnTe's H and S), and (b) warn about, and replace by its
Hermitian part, a full block that breaks the relation (the MoS2 position matrices, 6.2e-3 Angstrom), leaving exact
files untouched. All models here are generated from hBN_tb.dat; each defective file is run next to a twin
Hermitised BY HAND here, and the two outputs must agree.

Checks (orthonormal, both trees): exact hBN logs "Hermitian" and no WARNING; lower-triangle-only H is completed (log)
and equals the full model; a non-Hermitian H and a non-Hermitian r each give a WARNING naming the block and its
defect, and equal their hand-Hermitised twins, while differing from exact hBN (sensitivity); the repository MoS2
model, if present, warns with the known 6.19e-3 Angstrom. Non-orthonormal (only where opticx has the Orthonormal
keyword): a synthetic S with positions obeying the R S relation logs Hermitian; S stored as lower triangle only is
completed; positions that are Hermitian WITHOUT the R S term are flagged and repaired to the R S-consistent twin.
"""
import argparse, os, re, shutil, subprocess, sys
import numpy as np


def read_tb(fn):
    L = open(fn).read().split('\n')
    lat = [L[i] for i in (1, 2, 3)]
    norb, nR = int(L[4].split()[0]), int(L[5].split()[0])
    p, deg = 6, []
    while len(deg) < nR:
        deg += [int(x) for x in L[p].split()]; p += 1
    tok = iter(' '.join(L[p:]).split())
    Rs, H, RP = [], {}, {}
    for _ in range(nR):
        R = tuple(int(next(tok)) for _ in range(3)); Rs.append(R); M = np.zeros((norb, norb), complex)
        for _ in range(norb * norb):
            i, j = int(next(tok)) - 1, int(next(tok)) - 1; M[i, j] = float(next(tok)) + 1j * float(next(tok))
        H[R] = M
    for _ in range(nR):
        R = tuple(int(next(tok)) for _ in range(3)); M = np.zeros((3, norb, norb), complex)
        for _ in range(norb * norb):
            i, j = int(next(tok)) - 1, int(next(tok)) - 1
            v = [float(next(tok)) for _ in range(6)]; M[:, i, j] = [v[0] + 1j * v[1], v[2] + 1j * v[3], v[4] + 1j * v[5]]
        RP[R] = M
    return dict(lat=lat, latv=np.array([[float(x) for x in l.split()] for l in lat]), norb=norb, Rs=Rs, deg=deg, H=H, RP=RP)


def write_tb(fn, m, H, RP, S=None):
    norb, Rs = m['norb'], m['Rs']
    with open(fn, 'w') as f:
        f.write('generated by check_tb_hermiticity.py\n' + '\n'.join(m['lat']) + f'\n{norb}\n{len(Rs)}\n')
        for s in range(0, len(Rs), 15): f.write(' '.join(str(d) for d in m['deg'][s:s + 15]) + '\n')
        for R in Rs:
            f.write(f'\n{R[0]} {R[1]} {R[2]}\n')
            for j in range(norb):
                for i in range(norb): f.write(f'{i + 1} {j + 1} {H[R][i, j].real:.16e} {H[R][i, j].imag:.16e}\n')
        for R in Rs:
            f.write(f'\n{R[0]} {R[1]} {R[2]}\n')
            for j in range(norb):
                for i in range(norb):
                    f.write(f'{i + 1} {j + 1} ' + ' '.join(f'{RP[R][c, i, j].real:.16e} {RP[R][c, i, j].imag:.16e}' for c in range(3)) + '\n')
        if S is not None:
            for R in Rs:
                f.write(f'\n{R[0]} {R[1]} {R[2]}\n')
                for j in range(norb):
                    for i in range(norb): f.write(f'{i + 1} {j + 1} {S[R][i, j].real:.16e} {S[R][i, j].imag:.16e}\n')


INP = """# Periodic dimensions
2
# Wannier90_filename
{tb}
# Xatu_interface
false
# Ncells
12
# Bandlist
0 1
# Nfermi
1
# OME_sp
nonlinear
# Response
shift
# Energy_variables
5.0 10.0 0.2 26
{extra}"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--opticx', required=True); ap.add_argument('--root', default='.')
    ap.add_argument('--workdir', default='check_tb_hermiticity')
    a = ap.parse_args()
    root, work, opticx = os.path.abspath(a.root), os.path.abspath(a.workdir), os.path.abspath(a.opticx)
    shutil.rmtree(work, ignore_errors=True); os.makedirs(work)
    nonorth_ok = 'Orthonormal' in open(os.path.join(root, 'src', 'parser_input_file.f90')).read()
    nfail = 0

    def check(label, ok, msg=''):
        nonlocal nfail
        print(('  PASS   ' if ok else '  FAIL   ') + label + ('   ' + msg if msg else '')); nfail += 0 if ok else 1

    def run(name, H, RP, S=None, tbfile=None):
        d = os.path.join(work, name); os.makedirs(d)
        tb = tbfile or os.path.join(d, f'{name}_tb.dat')
        if tbfile is None: write_tb(tb, m, H, RP, S)
        extra = '# Orthonormal\nfalse\n' if S is not None else ''
        open(os.path.join(d, f'{name}.txt'), 'w').write(INP.format(tb=tb, extra=extra))
        r = subprocess.run([opticx, f'{name}.txt'], cwd=d, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        out = [f for f in os.listdir(d) if f.startswith('shift_sp_')]
        for f in os.listdir(d):
            if f.endswith('.omesp'): os.remove(os.path.join(d, f))
        sig = np.loadtxt(os.path.join(d, out[0]), comments='#')[:, 1:] if out else None
        return r.returncode, r.stdout, sig

    def rel(x, y):
        return np.abs(x - y).max() / np.abs(y).max()

    m = read_tb(os.path.join(root, 'hBN_tb.dat')); Rs, norb = m['Rs'], m['norb']
    H0 = {R: m['H'][R] for R in Rs}; RP0 = m['RP']
    mR = lambda R: tuple(-x for x in R)
    R1 = next(R for R in Rs if R != (0, 0, 0) and np.abs(H0[R][1, 0]) > 0.1)

    rc, log, s0 = run('exact', H0, RP0)
    check('exact hBN runs', rc == 0 and s0 is not None, f'rc={rc}')
    check('exact hBN: H and r logged Hermitian, no WARNING', 'H(R) Hermitian to' in log and 'position matrices r(R) Hermitian to' in log
          and 'WARNING (parser_wannier90_tb)' not in log)

    Hl = {R: np.tril(H0[R]) for R in Rs}
    rc, log, s = run('lower_H', Hl, RP0)
    check('lower-triangle-only H: completion logged, no WARNING', 'H(R) is stored as its lower triangle only' in log and 'WARNING (parser' not in log)
    check('lower-triangle-only H = full model', s is not None and rel(s, s0) < 1e-10, f'{rel(s, s0):.1e}' if s is not None else 'no output')

    delta = 0.05 + 0.03j                                               # eV, on H_21(R1) only
    Hb = {R: H0[R].copy() for R in Rs}; Hb[R1][1, 0] += delta
    Hh = {R: H0[R].copy() for R in Rs}; Hh[R1][1, 0] += delta / 2; Hh[mR(R1)][0, 1] += np.conj(delta) / 2
    rc, log, sb = run('nonherm_H', Hb, RP0); _, logh, sh = run('nonherm_H_twin', Hh, RP0)
    mm = re.search(r'H\(R\) not Hermitian: max defect\s+([0-9.E+-]+)', log)
    check('non-Hermitian H: WARNING with the defect size', mm is not None and abs(float(mm.group(1)) - abs(delta)) < 1e-3 * abs(delta),
          mm.group(1) if mm else 'no warning')
    check('non-Hermitian H = hand-Hermitised twin', sb is not None and rel(sb, sh) < 1e-10, f'{rel(sb, sh):.1e}' if sb is not None else '')
    check('twin logs Hermitian (no WARNING)', 'WARNING (parser' not in logh)
    check('sensitivity: the H defect changes the result', rel(sh, s0) > 1e-4, f'{rel(sh, s0):.1e}')

    # hBN's r(R) is diagonal; give it a Hermitian off-diagonal background first, otherwise a block whose upper
    # triangle is identically zero is (correctly) read as lower-triangle storage and completed, not averaged
    eps = 0.03 + 0.02j
    Rbase = {R: RP0[R].copy() for R in Rs}; Rbase[R1][0, 1, 0] += eps; Rbase[mR(R1)][0, 0, 1] += np.conj(eps)
    rc, log, sbase = run('offdiag_r', H0, Rbase)
    check('Hermitian off-diagonal r: logged Hermitian, no WARNING', rc == 0 and 'WARNING (parser' not in log)
    dr = 0.02 - 0.01j                                                  # Angstrom, on r^x_21(R1) only
    Rb = {R: Rbase[R].copy() for R in Rs}; Rb[R1][0, 1, 0] += dr
    Rh = {R: Rbase[R].copy() for R in Rs}; Rh[R1][0, 1, 0] += dr / 2; Rh[mR(R1)][0, 0, 1] += np.conj(dr) / 2
    rc, log, sb = run('nonherm_r', H0, Rb); _, logh, sh = run('nonherm_r_twin', H0, Rh)
    mm = re.search(r'position matrices r\(R\) not Hermitian: max defect\s+([0-9.E+-]+)', log)
    check('non-Hermitian r: WARNING with the defect size', mm is not None and abs(float(mm.group(1)) - abs(dr)) < 1e-3 * abs(dr),
          mm.group(1) if mm else 'no warning')
    check('non-Hermitian r = hand-Hermitised twin', sb is not None and rel(sb, sh) < 1e-10, f'{rel(sb, sh):.1e}' if sb is not None else '')
    check('sensitivity: the r defect changes the result', rel(sh, sbase) > 1e-5, f'{rel(sh, sbase):.1e}')

    mos = os.path.join(root, 'MoS2_spin_wannier_07032024_tb.dat')
    if os.path.exists(mos):
        d = os.path.join(work, 'MoS2_reader'); os.makedirs(d)
        open(os.path.join(d, 'MoS2_reader.txt'), 'w').write(INP.format(tb=mos, extra='').replace('Response\nshift', 'Response\nnone')
                                                            .replace('0 1\n# Nfermi\n1', '-1 0 1 2\n# Nfermi\n26').replace('Ncells\n12', 'Ncells\n3'))
        r = subprocess.run([opticx, 'MoS2_reader.txt'], cwd=d, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        mm = re.search(r'position matrices r\(R\) not Hermitian: max defect\s+([0-9.E+-]+)', r.stdout)
        check('MoS2 model: position-matrix WARNING, defect 6.19e-3 A', mm is not None and abs(float(mm.group(1)) - 6.192e-3) < 2e-6,
              mm.group(1) if mm else 'no warning')
    else:
        print('  SKIP   MoS2 model (MoS2_spin_wannier_07032024_tb.dat not in the root)')

    if nonorth_ok:
        lat = m['latv']; rng = np.random.default_rng(7)
        S = {}
        for R in Rs:                                                   # S(R) = delta_R0 + small Hermitian-consistent overlap
            if R == (0, 0, 0): S[R] = np.eye(norb, dtype=complex)
            elif mR(R) in S: S[R] = S[mR(R)].conj().T
            else: S[R] = 0.02 * (rng.standard_normal((norb, norb)) + 1j * rng.standard_normal((norb, norb))) * np.exp(-np.linalg.norm(np.array(R)))
        Rc = {R: np.array(R, float) @ lat for R in Rs}
        Rok = {R: RP0[R] + 0.5 * Rc[R][:, None, None] * S[R][None] for R in Rs}   # obeys r(R) = r(-R)^+ + R S(R)
        rc, log, sn = run('nonorth_exact', H0, Rok, S)
        check('non-orthonormal, R S-consistent positions: Hermitian, no WARNING', rc == 0 and 'WARNING (parser' not in log
              and 'S(R) Hermitian to' in log, f'rc={rc}')
        Sl = {R: np.tril(S[R]) for R in Rs}
        rc, log, s = run('nonorth_lower_S', H0, Rok, Sl)
        check('non-orthonormal, S as lower triangle: completion logged, no WARNING', 'S(R) is stored as its lower triangle only' in log
              and 'WARNING (parser' not in log)
        check('non-orthonormal, lower-triangle S = full S', s is not None and rel(s, sn) < 1e-10, f'{rel(s, sn):.1e}' if s is not None else '')
        rc, log, s = run('nonorth_plain_r', H0, RP0, S)                # Hermitian without the R S term: inconsistent
        check('non-orthonormal, positions missing the R S term: WARNING', 'position matrices r(R) not Hermitian' in log)
        check('... repaired to the R S-consistent twin', s is not None and rel(s, sn) < 1e-10, f'{rel(s, sn):.1e}' if s is not None else '')
    else:
        print('  SKIP   non-orthonormal checks (this tree has no Orthonormal keyword)')

    if nfail:
        print(f'\nFAILED: {nfail} check(s)'); sys.exit(1)
    print('\nALL CHECKS PASSED')


if __name__ == '__main__':
    main()
